"""Init

Revision ID: 5663c681db33
Revises: 
Create Date: 2024-01-19 16:32:02.937153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5663c681db33'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.String(length=10), nullable=False),
    sa.Column('course_class', sa.String(length=20), nullable=False),
    sa.Column('course_zh_name', sa.String(length=100), nullable=False),
    sa.Column('course_en_name', sa.String(length=100), nullable=False),
    sa.Column('course_syllabus', sa.String(length=200), nullable=True),
    sa.Column('course_type1', sa.String(length=20), nullable=True),
    sa.Column('course_type2', sa.String(length=20), nullable=True),
    sa.Column('course_fully_eng', sa.Boolean(), nullable=False),
    sa.Column('course_credit', sa.SmallInteger(), nullable=False),
    sa.Column('course_teacher_name', sa.String(length=20), nullable=True),
    sa.Column('course_teacher_link', sa.String(length=200), nullable=True),
    sa.Column('course_building', sa.String(length=50), nullable=True),
    sa.Column('course_time_and_loc', sa.String(length=100), nullable=True),
    sa.Column('course_student_limit', sa.SmallInteger(), nullable=False),
    sa.Column('course_student_registered', sa.SmallInteger(), nullable=False),
    sa.Column('course_student_selected', sa.SmallInteger(), nullable=False),
    sa.Column('course_can_cross_class', sa.String(length=10), nullable=True),
    sa.Column('course_note', sa.String(length=200), nullable=True),
    sa.Column('course_day_night', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_course_id'), 'courses', ['course_id'], unique=True)
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('course_week_times',
    sa.Column('week', sa.SmallInteger(), nullable=False),
    sa.Column('time', sa.SmallInteger(), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_week_times_course_id'), 'course_week_times', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_week_times_id'), 'course_week_times', ['id'], unique=True)
    op.create_table('user_course_maps',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_course_maps_course_id'), 'user_course_maps', ['course_id'], unique=False)
    op.create_index(op.f('ix_user_course_maps_id'), 'user_course_maps', ['id'], unique=True)
    op.create_index(op.f('ix_user_course_maps_user_id'), 'user_course_maps', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_course_maps_user_id'), table_name='user_course_maps')
    op.drop_index(op.f('ix_user_course_maps_id'), table_name='user_course_maps')
    op.drop_index(op.f('ix_user_course_maps_course_id'), table_name='user_course_maps')
    op.drop_table('user_course_maps')
    op.drop_index(op.f('ix_course_week_times_id'), table_name='course_week_times')
    op.drop_index(op.f('ix_course_week_times_course_id'), table_name='course_week_times')
    op.drop_table('course_week_times')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_course_id'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
